jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run ci
      - store_test_results:
          path: test-results.xml
  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run:
          # example curl request from dockerhub documentation
          name: Trigger docker remotely
          command: curl --data build=true -X POST $DOCKER_HUB_TRIGGER

version: 2.1

orbs:
  node: circleci/node@4.1.0

workflows:
  test:
    jobs:
      - test
  deploy:
    jobs:
      - deploy
